use std::{collections::HashSet, fmt::Display};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DataFieldType {
	UserIdentity,
	EmailAddress,
	Credential,
	NPI,
	PII,
}

impl Display for DataFieldType {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		let text = match self {
			Self::UserIdentity => "User Identity",
			Self::EmailAddress => "Email Address",
			Self::Credential => "Credential",
			Self::NPI => "Non-Public Information (NPI)",
			Self::PII => "Personally Identifying Information (PII)",
		};
		write!(f, "{}", text)
	}
}

impl DataFieldType {
	pub fn from_field_name(field_name: &str) -> Option<Self> {
		let data_field_mappings: HashSet<String, DataFieldType> = HashSet::from([
			("access_code", DataFieldType::Credential),
			("access_token", DataFieldType::Credential),
			("access_token", DataFieldType::Credential),
			("access_token", DataFieldType::Credential),
			("account_id", DataFieldType::UserIdentity),
			("account", DataFieldType::UserIdentity),
			("acct_id", DataFieldType::UserIdentity),
			("acct_name", DataFieldType::UserIdentity),
			("acct", DataFieldType::UserIdentity),
			("address", DataFieldType::PII),
			("api_key", DataFieldType::Credential),
			("auth_pass", DataFieldType::Credential),
			("auth_string", DataFieldType::Credential),
			("auth_token", DataFieldType::Credential),
			("auth_token", DataFieldType::Credential),
			("auth_token", DataFieldType::Credential),
			("auth", DataFieldType::Credential),
			("authcode", DataFieldType::Credential),
			("bank_account_number", DataFieldType::NPI),
			("bank_account", DataFieldType::NPI),
			("bcrypt", DataFieldType::Credential),
			("birthdate", DataFieldType::PII),
			("cc_number", DataFieldType::NPI),
			("ccn", DataFieldType::NPI),
			("cell", DataFieldType::PII),
			("client_id", DataFieldType::UserIdentity),
			("client_secret", DataFieldType::Credential),
			("contact_email", DataFieldType::EmailAddress),
			("contact_number", DataFieldType::PII),
			("contact_number", DataFieldType::PII),
			("credential", DataFieldType::Credential),
			("credit_card_number", DataFieldType::NPI),
			("credit_card", DataFieldType::NPI),
			("crypt", DataFieldType::Credential),
			("customer_id", DataFieldType::UserIdentity),
			("date_of_birth", DataFieldType::PII),
			("dl_number", DataFieldType::NationalId),
			("dob", DataFieldType::PII),
			("driver_license", DataFieldType::NationalId),
			("e_mail", DataFieldType::EmailAddress),
			("email_address", DataFieldType::EmailAddress),
			("email_address", DataFieldType::EmailAddress),
			("email_login", DataFieldType::EmailAddress),
			("email", DataFieldType::EmailAddress),
			("emailaddr", DataFieldType::EmailAddress),
			("first_name", DataFieldType::UserIdentity),
			("fname", DataFieldType::UserIdentity),
			("full_name", DataFieldType::UserIdentity),
			("gid", DataFieldType::UserIdentity),
			("given_name", DataFieldType::UserIdentity),
			("govid", DataFieldType::NationalId),
			("guid", DataFieldType::UserIdentity),
			("handle", DataFieldType::UserIdentity),
			("hash", DataFieldType::Credential),
			("home_address", DataFieldType::PII),
			("id_number", DataFieldType::NationalId),
			("id", DataFieldType::UserIdentity),
			("identity", DataFieldType::UserIdentity),
			("last_name", DataFieldType::UserIdentity),
			("lname", DataFieldType::UserIdentity),
			("login_name", DataFieldType::UserIdentity),
			("login_pass", DataFieldType::Credential),
			("login", DataFieldType::UserIdentity),
			("mail_addr", DataFieldType::EmailAddress),
			("mail", DataFieldType::EmailAddress),
			("md5pass", DataFieldType::Credential),
			("member_id", DataFieldType::UserIdentity),
			("member_id", DataFieldType::UserIdentity),
			("member", DataFieldType::UserIdentity),
			("mobile", DataFieldType::PII),
			("msisdn", DataFieldType::PII),
			("national_id", DataFieldType::NationalId),
			("nickname", DataFieldType::UserIdentity),
			("pass_hash", DataFieldType::Credential),
			("pass_md5", DataFieldType::Credential),
			("pass_word", DataFieldType::Credential),
			("pass", DataFieldType::Credential),
			("passcode", DataFieldType::Credential),
			("passport", DataFieldType::NationalId),
			("passw", DataFieldType::Credential),
			("passwd", DataFieldType::Credential),
			("passwd", DataFieldType::Credential),
			("password_hash", DataFieldType::Credential),
			("password_hash", DataFieldType::Credential),
			("password", DataFieldType::Credential),
			("password", DataFieldType::Credential),
			("person_id", DataFieldType::UserIdentity),
			("phone_number", DataFieldType::PII),
			("phone", DataFieldType::PII),
			("phone", DataFieldType::PII),
			("pid", DataFieldType::UserIdentity),
			("primary_email", DataFieldType::EmailAddress),
			("profile_name", DataFieldType::UserIdentity),
			("profile", DataFieldType::UserIdentity),
			("pswd", DataFieldType::Credential),
			("pw_hash", DataFieldType::Credential),
			("pw", DataFieldType::Credential),
			("pwd_hash", DataFieldType::Credential),
			("pwd", DataFieldType::Credential),
			("pwhash", DataFieldType::Credential),
			("pword", DataFieldType::Credential),
			("realname", DataFieldType::UserIdentity),
			("refresh_token", DataFieldType::Credential),
			("remember_token", DataFieldType::Credential),
			("residential_address", DataFieldType::PII),
			("routing_number", DataFieldType::NPI),
			("screen_name", DataFieldType::UserIdentity),
			("secret", DataFieldType::Credential),
			("session_token", DataFieldType::Credential),
			("sha1_pass", DataFieldType::Credential),
			("sha256_pass", DataFieldType::Credential),
			("shadow", DataFieldType::Credential),
			("sin", DataFieldType::NationalId),
			("social_security_number", DataFieldType::PII),
			("social", DataFieldType::PII),
			("ssn", DataFieldType::NationalId),
			("ssn", DataFieldType::NationalId),
			("surname", DataFieldType::UserIdentity),
			("tel", DataFieldType::PII),
			("token", DataFieldType::Credential),
			("token", DataFieldType::Credential),
			("uid", DataFieldType::UserIdentity),
			("user_email", DataFieldType::EmailAddress),
			("user_id", DataFieldType::UserIdentity),
			("user_pass", DataFieldType::Credential),
			("user_pw", DataFieldType::Credential),
			("user", DataFieldType::UserIdentity),
			("userid", DataFieldType::UserIdentity),
			("username", DataFieldType::UserIdentity),
			("uuid", DataFieldType::UserIdentity),
		]);

		let field_name_lower = field_name.to_lowercase();
	}
}
