use std::collections::HashMap;

use crate::analyze::{datafile::DataFieldType, detection::npi_detection::NPIType};

pub const DATA_FIELD_MAPPINGS: HashMap<&'static str, DataFieldType> = HashMap::from([
	// =========================
	// Credential
	// =========================
	("access_code", DataFieldType::Credential),
	("access_token", DataFieldType::Credential),
	("api_key", DataFieldType::Credential),
	("api_secret", DataFieldType::Credential),
	("auth", DataFieldType::Credential),
	("auth_pass", DataFieldType::Credential),
	("auth_string", DataFieldType::Credential),
	("auth_token", DataFieldType::Credential),
	("authcode", DataFieldType::Credential),
	("authorization_code", DataFieldType::Credential),
	("bearer_token", DataFieldType::Credential),
	("bcrypt", DataFieldType::Credential),
	("cleartext_password", DataFieldType::Credential),
	("client_secret", DataFieldType::Credential),
	("credential", DataFieldType::Credential),
	("crypt", DataFieldType::Credential),
	("csrf_token", DataFieldType::Credential),
	("hash", DataFieldType::Credential),
	("hash_pass", DataFieldType::Credential),
	("hash_passwd", DataFieldType::Credential),
	("id_token", DataFieldType::Credential),
	("jwt", DataFieldType::Credential),
	("jwt_token", DataFieldType::Credential),
	("login_pass", DataFieldType::Credential),
	("md5pass", DataFieldType::Credential),
	("mfa_code", DataFieldType::Credential),
	("one_time_password", DataFieldType::Credential),
	("oauth_token", DataFieldType::Credential),
	("otp", DataFieldType::Credential),
	("pass", DataFieldType::Credential),
	("pass_hash", DataFieldType::Credential),
	("pass_md5", DataFieldType::Credential),
	("pass_word", DataFieldType::Credential),
	("passcode", DataFieldType::Credential),
	("passwd", DataFieldType::Credential),
	("password", DataFieldType::Credential),
	("password_hash", DataFieldType::Credential),
	("plaintext_pass", DataFieldType::Credential),
	("pswd", DataFieldType::Credential),
	("pw", DataFieldType::Credential),
	("pw_hash", DataFieldType::Credential),
	("pwd", DataFieldType::Credential),
	("pwd_hash", DataFieldType::Credential),
	("pwhash", DataFieldType::Credential),
	("pword", DataFieldType::Credential),
	("raw_password", DataFieldType::Credential),
	("refresh_token", DataFieldType::Credential),
	("remember_token", DataFieldType::Credential),
	("secret", DataFieldType::Credential),
	("session_token", DataFieldType::Credential),
	("sha1_pass", DataFieldType::Credential),
	("sha256_pass", DataFieldType::Credential),
	("sha512_pass", DataFieldType::Credential),
	("shadow", DataFieldType::Credential),
	("token", DataFieldType::Credential),
	("totp", DataFieldType::Credential),
	("user_pass", DataFieldType::Credential),
	("user_pw", DataFieldType::Credential),
	("xsrf_token", DataFieldType::Credential),
	// =========================
	// SecureCredential
	// =========================
	("argon2_hash", DataFieldType::SecureCredential),
	("bcrypt_hash", DataFieldType::SecureCredential),
	("id_ed25519", DataFieldType::SecureCredential),
	("id_rsa", DataFieldType::SecureCredential),
	("password_salt", DataFieldType::SecureCredential),
	("pw_salt", DataFieldType::SecureCredential),
	("salt", DataFieldType::SecureCredential),
	("scrypt_hash", DataFieldType::SecureCredential),
	("secret_key", DataFieldType::SecureCredential),
	("session_id", DataFieldType::SecureCredential),
	("session_key", DataFieldType::SecureCredential),
	("ssh_private_key", DataFieldType::SecureCredential),
	("token_hash", DataFieldType::SecureCredential),
	("private_key", DataFieldType::SecureCredential),
	// =========================
	// UserIdentity
	// =========================
	("account", DataFieldType::UserIdentity),
	("acct", DataFieldType::UserIdentity),
	("acct_name", DataFieldType::UserIdentity),
	("full_user_name", DataFieldType::UserIdentity),
	("full_username", DataFieldType::UserIdentity),
	("identity", DataFieldType::UserIdentity),
	("login", DataFieldType::UserIdentity),
	("login_name", DataFieldType::UserIdentity),
	("member", DataFieldType::UserIdentity),
	("operator_id", DataFieldType::UserRecordNumber),
	("pid", DataFieldType::UserIdentity),
	("profile", DataFieldType::UserIdentity),
	("profile_id", DataFieldType::UserIdentity),
	("screen_name", DataFieldType::UserIdentity),
	("sub", DataFieldType::UserRecordNumber),
	("subject", DataFieldType::UserRecordNumber),
	("user", DataFieldType::UserIdentity),
	("user_id", DataFieldType::UserIdentity),
	("username", DataFieldType::UserIdentity),
	// =========================
	// UserRecordNumber
	// =========================
	("account_guid", DataFieldType::UserRecordNumber),
	("account_id", DataFieldType::UserRecordNumber),
	("account_uuid", DataFieldType::UserRecordNumber),
	("acct_id", DataFieldType::UserRecordNumber),
	("client_id", DataFieldType::UserRecordNumber),
	("customer_id", DataFieldType::UserRecordNumber),
	("full_user_id", DataFieldType::UserRecordNumber),
	("gid", DataFieldType::UserRecordNumber),
	("id", DataFieldType::UserRecordNumber),
	("login_id", DataFieldType::UserRecordNumber),
	("member_id", DataFieldType::UserRecordNumber),
	("member_number", DataFieldType::UserRecordNumber),
	("person_id", DataFieldType::UserRecordNumber),
	("principal_id", DataFieldType::UserRecordNumber),
	("user_guid", DataFieldType::UserRecordNumber),
	("user_uuid", DataFieldType::UserRecordNumber),
	("userid", DataFieldType::UserRecordNumber),
	// =========================
	// NPI
	// =========================
	("alias", DataFieldType::NPI(NPIType::OtherIdentity("Alias"))),
	(
		"nick",
		DataFieldType::NPI(NPIType::OtherIdentity("Nickname")),
	),
	(
		"nickname",
		DataFieldType::NPI(NPIType::OtherIdentity("Nickname")),
	),
	(
		"handle",
		DataFieldType::NPI(NPIType::OtherIdentity("Social Media Handle")),
	),
	(
		"tenant_id",
		DataFieldType::NPI(NPIType::OtherRecordNumber("Tenant")),
	),
	(
		"org_id",
		DataFieldType::NPI(NPIType::OtherRecordNumber("Organization")),
	),
	(
		"organization_id",
		DataFieldType::NPI(NPIType::OtherRecordNumber("Organization")),
	),
	(
		"workspace_id",
		DataFieldType::NPI(NPIType::OtherRecordNumber("Workspace")),
	),
	("wallet_address", DataFieldType::NPI(NPIType::AccountNumber)),
	("btc_address", DataFieldType::NPI(NPIType::AccountNumber)),
	("eth_address", DataFieldType::NPI(NPIType::AccountNumber)),
	("crypto_address", DataFieldType::NPI(NPIType::AccountNumber)),
	(
		"tax_id",
		DataFieldType::NPI(NPIType::OtherIdentificationNumber("Tax Id")),
	),
	(
		"ein",
		DataFieldType::NPI(NPIType::OtherIdentificationNumber("Employer Tax Id")),
	),
	(
		"vat_number",
		DataFieldType::NPI(NPIType::OtherIdentificationNumber("Vat")),
	),
	(
		"routing_number",
		DataFieldType::NPI(NPIType::BankRoutingNumber),
	),
	(
		"bank_routing_number",
		DataFieldType::NPI(NPIType::BankRoutingNumber),
	),
	(
		"routing_num",
		DataFieldType::NPI(NPIType::BankRoutingNumber),
	),
	("routing_nr", DataFieldType::NPI(NPIType::BankRoutingNumber)),
]);
